music_directory "~/playlists"
playlist_directory "~/playlists/lists"
user "zshleyp"
restore_paused "no"
log_file "~/.Trash/log"
pid_file "~/.mpd"

audio_output {
    type "osx"
    name "CoreAudio"
    format "44100:16:2"
}

audio_output {
   type   "fifo"
   name   "my_fifo"
   path   "/tmp/mpd.fifo"
   format "44100:16:2"
}
