palette = "adachi-rei"

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Starship modules
[character]
# Note the use of Catppuccin color 'peach'
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](subtext1)" # For use with zsh-vi-mode

[git_branch]
style = "bold mauve"

[directory]
truncation_length = 4
style = "bold blue"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[palettes.adachi-rei]

red = "#ff2300"
maroon = "#ff2300"

peach = "#ff4600"
yellow = "#ff4600"

green = "#c8dcc8"

teal = "#94e2d5"
sky = "#89dceb"

sapphire = "#c8c8dc"
blue = "#c8c8dc"

lavender = "#d2c8d2"
mauve = "#d2c8d2"

text = "#c8c8c8"
subtext1 = "#c8c8c8"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#101010"
mantle = "#101010"
crust = "#101010"
